[package]
name = "arksync-sensor"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# [lib]
# name = "arksync_lib"
# crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serialport = "4.8.1"
tokio = { version = "1.49.0", features = ["full"] }
